### ISSUE TITLE
Blips not appearing on map

### ISSUE THREAD

**Issue by gamerbiggie** [gimicze/policetools#1]
*Edit* oops submitted before writing anything.. my bad

Hello there! Currently seem to be having an issue where the blips don't show. I admit I changed the code slightly.

`if (xPlayer.job.name == "police" or xPlayer.job.name == "ambulance" or xPlayer.job.name == "doc")`
Instead of 
`if xPlayer.job.name == Config.UnitsRadar.enableESX`

As I have more than the Police needing the blips.

Also changed the item name from `gps` to `policegps`

That is all that was changed and using the latest Release instead of a pull from the panic update.

The /callsign works, pops up saying the callsign etc. I have OneSync enabled on the server and cleared cache too, no errors either

**Comment by gimicze** [comment]
Hello! 

Please post the whole snippets of your edited code. Also, does adding players manually using /playerblip add <server ID> work?

**Comment by gamerbiggie** [comment]
This is the entire bit that was edited, literally just the if statements :P 

`if Config.UnitsRadar.enableESX then
    ESX = nil

    TriggerEvent('esx:getSharedObject', function(obj) ESX = obj end)

    Config.UnitsRadar.requireItem = tostring(Config.UnitsRadar.requireItem)

    RegisterNetEvent("esx:setJob")
    AddEventHandler(
        "esx:setJob",
        function(source)
            local xPlayer = ESX.GetPlayerFromId(source)
    
            if (xPlayer.job.name == "police" or xPlayer.job.name == "ambulance" or xPlayer.job.name == "doc") and (not Config.UnitsRadar.requireItem or xPlayer.getInventoryItem(Config.UnitsRadar.requireItem).count > 0) then
                UnitsRadar:addUnit(source)
            elseif UnitsRadar.active[source] then
                UnitsRadar:removeUnit(source)
            end
        end
    )
    
    RegisterNetEvent("esx:playerLoaded")
    AddEventHandler(
        "esx:playerLoaded",
        function(source, xPlayer)
            if (xPlayer.job.name == "police" or xPlayer.job.name == "ambulance" or xPlayer.job.name == "doc") and not UnitsRadar.active[source] and (not Config.UnitsRadar.requireItem or xPlayer.getInventoryItem(Config.UnitsRadar.requireItem).count > 0) then
                UnitsRadar:addUnit(source)
            elseif UnitsRadar.active[source] then
                UnitsRadar:removeUnit(source)
            end
        end
    )

    if Config.UnitsRadar.requireItem then
        ESX.RegisterUsableItem(
            Config.UnitsRadar.requireItem,
            function(source)
                local xPlayer = ESX.GetPlayerFromId(source)

                if (xPlayer.job.name == "police" or xPlayer.job.name == "ambulance" or xPlayer.job.name == "doc") and not UnitsRadar.active[source] then
                    UnitsRadar:addUnit(source)
                elseif UnitsRadar.active[source] then
                    UnitsRadar:removeUnit(source)
                end
            end
        )
    end
end`

Used /policeblip add but didnt do anything either. Funny enough it worked once then just stopped after a restart of the server etc

**Comment by gimicze** [comment]
Have you tried reinstalling from the latest release? I know it doesn't suit your needs, but it's a good starting point to determining where the error is.

**Comment by gamerbiggie** [comment]
Okay, so i reinstalled it fresh, tried all the commands, (add, show, on etc) and nothing on map still. still no errors at all either

**Comment by gimicze** [comment]
Are you testing the script on other players aswell? You won't see your own blip. Please try installing the latest version, in which I've added the ability to choose more than one job. (enter a table listing the jobs instead of supplying only a name of a single job - instructions added in config).

**Comment by gamerbiggie** [comment]
Yeah testing with a 2nd player :)

Will grab the latest and take a look!

**Comment by gamerbiggie** [comment]
Okay tested it, blips stil ldont seem to show up on map. tried all the commands too

**Comment by gamerbiggie** [comment]
Testing if I remove the need to have the item fixed it, will report back in bit :)

**Comment by gimicze** [comment]
Do you have Discord? It would probably be better to discuss this in a call.

Disabling the item won't help - the commands ignore the config and should force add any player you specify.

(My tag is GIMI#5227, feel free to add me)

**Comment by gimicze** [comment]
The RegisterKeyMapping native was acting up, causing the script not to load properly. This is unfortunately a problem of the latest FXServer artifact and we'll have to wait for the fix.

Thank you for testing it out!
