### ISSUE TITLE
ESX jobs + Policeblip add

### ISSUE THREAD

**Issue by gonzalo658** [gimicze/policetools#2]
So when doing :
 ` enableESX = 'police',`
 
 It does not find the police "role" it totaly ignores it and makes the hole server use the `/policeblip add` command

--
 
 And when using /policeblip add whitout any id. it does not add you. 
 
 Any ideas? i Gladly go trough this on discord with you if you want. 
 
 Great script overall

**Comment by gimicze** [comment]
Please try downloading [the latest code](https://github.com/gimicze/policetools/archive/refs/heads/main.zip) (not release!) and see if that resolves anything. If not, have a look in the client & server console for any errors. 

Changes in the latest code should also resolve the /policeblip command bug which you described.

Thank you :-)

**Comment by gimicze** [comment]
Non-reproducible.
