### ISSUE TITLE
(global 'ESX')

### ISSUE THREAD

**Issue by Feccys** [gimicze/policetools#8]
![image](https://user-images.githubusercontent.com/64001294/236636890-94b230ba-3f89-4ee1-8392-748ae5a32b2a.png)

**Comment by gimicze** [comment]
Hi!

Which version of ESX are you running?

Please try updating the script using the current code (download code from the homepage of the repository instead of downloading it on the releases page).

**Comment by Feccys** [comment]
I use ESX legacy
